-- Tests/tools/bundle_profile.lua
-- Re-pack an in-game export (a NOCK1: string saved to a text file) sanitized
-- against the shipped Defaults and write Config/ProfilesBundled.lua with it as
-- the "Yaxal" entry. Run from the repo root:
--   luajit Tests/tools/bundle_profile.lua <path-to-export.txt> [version] [drop=key,key]
-- `drop=` names keys to leave out: a value that WAS the default when the
-- string was exported but whose default has since moved (a list that grew)
-- would otherwise pin the bundle to the old value.
-- Stale keys an older Nock left in the exporter's SavedVariables are dropped
-- here, so the bundle test (zero drops against Defaults) stays green. Keys
-- equal to their Default are dropped too: a bundle is the DIFF from the
-- shipped Defaults, so a default that changes later (a new Tranq ID, say)
-- reaches the bundled profile instead of being pinned to the old value.
dofile("Libs/LibStub/LibStub.lua")
dofile("Libs/AceSerializer-3.0/AceSerializer-3.0.lua")
dofile("Libs/LibDeflate/LibDeflate.lua")
local real = { state = {} }
local realLibStub = LibStub
_G.LibStub = setmetatable({}, { __call = function(_, n, s) if n == "AceAddon-3.0" then return { GetAddon = function() return real end } end return realLibStub(n, s) end })
dofile("Core/Constants.lua")
dofile("Config/Defaults.lua")
dofile("Core/ProfileShare.lua")
_G.LibStub = realLibStub
local f = assert(io.open(arg[1], "rb")); local s = f:read("*a"); f:close()
s = s:gsub("%s+$", "")
local PS = real.ProfileShare
local payload = assert(PS.Unpack(s))
local clean, dropped = PS.Sanitize(payload.profile, real.Defaults.profile, {})
local function same(a, b)
  if type(a) ~= type(b) then return false end
  if type(a) ~= "table" then return a == b end
  for k, v in pairs(a) do if not same(v, b[k]) then return false end end
  for k in pairs(b) do if a[k] == nil then return false end end
  return true
end
local pruned = 0
for i = 3, #arg do
  local list = arg[i]:match("^drop=(.+)$")
  if list then for k in list:gmatch("[^,]+") do clean[k] = nil end end
end
for k, v in pairs(real.Defaults.profile) do
  if clean[k] ~= nil and same(clean[k], v) then clean[k] = nil; pruned = pruned + 1 end
end
local version = arg[2] or "2.0.0-alpha.2"
local packed = PS.Pack(clean, "Yaxal", version, {})
local again, d2 = PS.Sanitize(assert(PS.Unpack(packed)).profile, real.Defaults.profile, {})
assert(#d2 == 0, "repacked string still drops keys")
assert(not packed:find('"') and not packed:find("\\"), "unsafe characters in the packed string")
local n = 0; for _ in pairs(clean) do n = n + 1 end
local out = assert(io.open("Config/ProfilesBundled.lua", "wb"))
out:write([[
-- Config/ProfilesBundled.lua
-- Profiles that ship inside Nock, as export strings (Modules/ProfileShare.lua
-- applies them through the same importer a pasted string goes through). To add
-- or refresh one: in game, Profiles -> Sharing -> Export as text, copy the
-- string into `data`, set `version` to the Nock version it came from. Never
-- the user's default: applying one always makes a new named profile, and the
-- wizard's start page offers them next to "Start from scratch".
-- Tests/profile_share_test.lua decodes every entry against the current
-- Defaults, so a stale string fails the suite rather than a user. Generated by
-- Tests/tools/bundle_profile.lua, which re-packs the export sanitized (no keys
-- an older Nock left behind, no session flags) and as a DIFF from Defaults,
-- so a default that changes later reaches the bundled profile too.

local Nock = LibStub("AceAddon-3.0"):GetAddon("Nock")

Nock.BundledProfiles = {
  {
    key = "yaxal", name = "Yaxal", author = "Yaxal", version = "]] .. version .. [[",
    blurb = "The author's own setup: React HUD, weaver, every tracker and helper on, as run on raid nights.",
    data = "]] .. packed .. [[",
  },
}
]])
out:close()
print(("bundled: %d keys kept, %d stale dropped, %d default-equal pruned, %d chars"):format(n, #dropped, pruned, #packed))
