-- Config/OptionsLayoutData.lua
-- GENERATED by Tests/tools/edits_to_layout.py from the design canvas' edits; do not edit by hand.
-- Per tab: header cards (name, icon, desc, rows in order, actions, table/form/stack/segments, advanced), renames and one-liners.
local Nock = LibStub("AceAddon-3.0"):GetAddon("Nock")
local C = Nock.Constants.SpellID
local L = {}
Nock.OptionsLayoutData = L

L.GLOBAL_RENAME = {
  showAutoShotBar = "Auto Shot bar",
  showMeleeBar = "Melee swing timer",
  showGcdBar = "GCD bar",
  showManaBar = "Mana bar",
  showRotation = "Rotation display",
  rotationHelperEnabled = "Rotation helper",
  showWindupMark = "Wind-up mark",
  editGridShow = "Grid while unlocked",
  showAutoShotCast = "Auto Shot in cast bar",
  castBarNonCombatCasts = "Non-combat casts",
  backgroundEnabled = "Background",
  consumeBannerEnabled = "Pill while eating or drinking",
  playerEnabled = "Player buffs panel",
  petEnabled = "Pet buffs panel",
  raidOnly = "Raids only",
  trackerEnabled = "Tracker section",
  clickerEnabled = "Tank buttons",
  showCompleted = "Stocked items too",
  repairEnabled = "Repair reminder",
  weaveBindEnabled = "Weave bind",
  tonkDialEnabled = "Countdown dial",
  practiceToast = "Toast",
  practiceTimelineOkMarks = "OK marks too",
  releaseBarEnabled = "Retry-Timer",
  fluffyShowAutoShotCast = "Auto Shot wind-up as a cast",
  shotBarsShowMulti = "Multi-Shot window",
  shotBarsShowArcane = "Arcane Shot window",
  shotBarsShowRaptor = "Melee weave lane",
  autoShotDelayEnabled = "Auto Shot delay (experimental)",
  activePreview = "Preview: light every tile",
  forceShaman = "Panel with no shaman",
  hudEnabled = "HUD",
  rb_en_weave = "Weave stage",
  shotBarsShowHelper = "Next-action helper row",
}
L.PATH_RENAME = {
  ["hud.classic.rotation.masterToggle"] = "Rotation display",
  ["alerts.warnings.masterToggle"] = "Warnings panel",
  ["alerts.helpers.tabSettings.masterToggle"] = "Helpers panel",
}
L.CHIPS = { "recipients", "tankList", "zones", "customPlayer", "customPet", "custom" }
L.SEGMENTED = { "settingsScale", "pvpMode" }

L.TABS = {
  {
    path = "alerts.aggro",
    cards = {
      { key = "flashCard", name = "Flash", icon = { glyph = "warn" }, desc = "A red starburst at screen centre while a mob is on you; drag it while frames are unlocked.", actions = { "aggroPreviewFlash", "aggroResetPos" }, rows = { "aggroEnabled", "aggroGroupOnly", "aggroSize", "aggroColor", "aggroPulse", "aggroTexture", "aggroPreviewFlash", "aggroResetPos" } },
      { key = "voiceCard", name = "Voice", icon = { glyph = "bell" }, desc = "Auto tries WeakAuras' aggro clip if you have that addon, then the game's speech, then the picked sound.", actions = { "aggroPreview" }, rows = { "aggroSoundMode", "aggroSound", "aggroPreview", "aggroSoundFile", "aggroSpeechText", "aggroSoundChannel" } },
    },
    rename = { aggroEnabled = "Aggro warning", aggroSoundMode = "Cue", aggroPreview = "Preview", aggroPreviewFlash = "Preview" },
  },
  {
    path = "trackers.buffTracker",
    cards = {
      { key = "buffTrackerCard", name = "Buff tracker", icon = { glyph = "shield" }, desc = "A compact icon grid of the buffs on you and your pet, OmniCC-friendly.", rows = { "enabled", "cols", "iconSize" } },
      { key = "panelsCard", name = "Panels", icon = { glyph = "layers" }, desc = "Two panels, each placed on its own while frames are unlocked.", table = { cols = { { "Shown" }, { "Position" } }, rows = { { "Player buffs", { ["Shown"] = "playerEnabled", ["Position"] = "playerResetPos" } }, { "Pet buffs", { ["Shown"] = "petEnabled", ["Position"] = "petResetPos" } } } }, rows = { "playerEnabled", "playerResetPos", "petEnabled", "petResetPos" } },
      { key = "showWhenCard", name = "Show when", icon = { glyph = "eyeoff" }, desc = "Hide the tracker where it is no use; an unlocked tracker always shows so you can place it.", rows = { "buffTrackerHideRested", "buffTrackerHideSolo", "buffTrackerShowParty", "buffTrackerShowRaid" } },
      { key = "missingHighlightCard", name = "Missing highlight", icon = { glyph = "sparkle" }, advanced = true, rows = { "buffTrackerMissingEffect", "buffTrackerMissingColor" } },
      { key = "backgroundCard", name = "Background", icon = { glyph = "square" }, advanced = true, rows = { "buffTrackerBgColor", "buffTrackerBgOpacity", "buffTrackerBorder", "buffTrackerBorderSize", "buffTrackerBorderColor", "buffTrackerBorderOpacity" } },
      { key = "trackedBuffsCard", name = "Tracked buffs", icon = { glyph = "stack" }, desc = "The preset list plus your own spell IDs.", actions = { "restorePreset" }, rows = { "restorePreset", "customPlayer", "customPet" } },
    },
    rename = { enabled = "Buff tracker", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", customPlayer = "Custom player buffs", customPet = "Custom pet buffs", playerResetPos = "Reset", petResetPos = "Reset", buffTrackerHideRested = "Hide while rested", buffTrackerHideSolo = "Hide when not in a group", buffTrackerShowParty = "Dungeon group counts", buffTrackerShowRaid = "Raid group counts" },
  },
  {
    path = "hud.classic.swingBars",
    cards = {
      { key = "autoShotBarCard", name = "Auto Shot bar", icon = { spell = C.AUTO_SHOT }, desc = "The tall ranged swing bar.", rows = { "showAutoShotBar", "autoShotShowIcon", "autoShotBarRotationText", "autoShotBarHeight", "autoShotBarTexture", "autoShotBarColor" } },
      { key = "clipTicksCard", name = "Clip ticks", icon = { glyph = "ruler" }, desc = "Where a Steady or Multi cast would clip the next Auto Shot.", advanced = true, table = { cols = { { "Colour", "Color" }, { "Width", "Width" } }, rows = { { "Steady", "clipTickSteady" }, { "Multi", "clipTickMulti" }, { "Wind-up", "clipTickWindup" } } }, rows = { "clipTickSteadyColor", "clipTickSteadyWidth", "clipTickMultiColor", "clipTickMultiWidth", "clipTickWindupColor", "clipTickWindupWidth", "autoShotDelayEnabled" } },
      { key = "meleeBarCard", name = "Melee bar", icon = { spell = C.RAPTOR_STRIKE }, desc = "The melee swing timer for weaving.", rows = { "showMeleeBar", "meleeShowIcon", "meleeBarHeight", "meleeBarTexture", "meleeBarColor" } },
      { key = "gcdBarCard", name = "GCD bar", icon = { glyph = "clock" }, rows = { "showGcdBar", "gcdBarHeight", "gcdBarColor" } },
      { key = "fillDirectionCard", name = "Fill direction", icon = { glyph = "expand" }, rows = { "swingFillDirection", "swingFillDirectionRanged", "swingFillDirectionMelee", "swingFillDirectionGcd" } },
      { key = "trackBackgroundCard", name = "Track background", icon = { glyph = "square" }, advanced = true, table = { cols = { { "Background", "TrackBgColor", "TrackBgOpacity" }, { "Border", "TrackBorderColor", "TrackBorderOpacity" } }, rows = { { "Auto Shot bar", "autoShot" }, { "Melee bar", "melee" }, { "GCD bar", "gcd" } } }, rows = { "autoShotTrackBgColor", "autoShotTrackBgOpacity", "autoShotTrackBorderColor", "autoShotTrackBorderOpacity", "meleeTrackBgColor", "meleeTrackBgOpacity", "meleeTrackBorderColor", "meleeTrackBorderOpacity", "gcdTrackBgColor", "gcdTrackBgOpacity", "gcdTrackBorderColor", "gcdTrackBorderOpacity" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", enabled = "Totem tracker", castBarAutoShotColor = "Auto Shot wind-up colour" },
    desc = { showAutoShotBar = "The tall ranged bar with the icon, clip ticks and rotation text.", showMeleeBar = "The melee swing timer, with the Raptor Strike icon.", forceShaman = "Show the panel with no shaman in the group, for placing it." },
  },
  {
    path = "hud.classic.rangeFinder",
    cards = {
      { key = "barCard", name = "Bar", icon = { spell = C.HUNTERS_MARK }, desc = "The range strip under the bars.", rows = { "rangeFinderFindingStyle", "rangeFinderHeight" } },
      { key = "coloursCard", name = "Colours", icon = { glyph = "palette" }, advanced = true, rows = { "rangeOutColor", "rangeInColor", "rangePerfectColor", "rangeCloseColor" } },
      { key = "trackBackgroundCard", name = "Track background", icon = { glyph = "square" }, advanced = true, table = { cols = { { "Background", "TrackBgColor", "TrackBgOpacity" }, { "Border", "TrackBorderColor", "TrackBorderOpacity" } }, rows = { { "Range finder", "range" } } }, rows = { "rangeTrackBgColor", "rangeTrackBgOpacity", "rangeTrackBorderColor", "rangeTrackBorderOpacity" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", enabled = "Totem tracker", castBarAutoShotColor = "Auto Shot wind-up colour" },
    desc = { showAutoShotBar = "The tall ranged bar with the icon, clip ticks and rotation text.", showMeleeBar = "The melee swing timer, with the Raptor Strike icon.", forceShaman = "Show the panel with no shaman in the group, for placing it." },
  },
  {
    path = "hud.classic.manaBar",
    cards = {
      { key = "barCard", name = "Bar", icon = { spell = 34074 }, rows = { "showManaBar", "manaBarText", "manaBarHeight", "manaBarColor" } },
      { key = "manaTickCard", name = "Mana tick", icon = { glyph = "bolt" }, desc = "The five-second-rule spark.", rows = { "showManaTick", "manaTickColor", "manaTickDirCombat", "manaTickDirOoc" } },
      { key = "trackBackgroundCard", name = "Track background", icon = { glyph = "square" }, advanced = true, table = { cols = { { "Background", "TrackBgColor", "TrackBgOpacity" }, { "Border", "TrackBorderColor", "TrackBorderOpacity" } }, rows = { { "Mana bar", "mana" } } }, rows = { "manaTrackBgColor", "manaTrackBgOpacity", "manaTrackBorderColor", "manaTrackBorderOpacity" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", enabled = "Totem tracker", castBarAutoShotColor = "Auto Shot wind-up colour" },
    desc = { showAutoShotBar = "The tall ranged bar with the icon, clip ticks and rotation text.", showMeleeBar = "The melee swing timer, with the Raptor Strike icon.", forceShaman = "Show the panel with no shaman in the group, for placing it." },
  },
  {
    path = "hud.classic.castBar",
    cards = {
      { key = "barCard", name = "Bar", icon = { spell = C.STEADY_SHOT }, desc = "What the cast bar shows; the same switches as General > Cast bar.", rows = { "showAutoShotCast", "castBarNonCombatCasts", "hideBlizzardCastBar" } },
      { key = "lookCard", name = "Look", icon = { glyph = "palette" }, desc = "Icon, height, texture and fill colour of the classic cast bar.", stack = true, rows = { "castBarShowIcon", "castBarHeight", "castBarTexture", "castBarColor", "castBarAutoShotColor" } },
      { key = "frameCard", name = "Frame", icon = { glyph = "square" }, advanced = true, table = { cols = { { "Background", "BgColor", "BgOpacity" }, { "Border", "BorderColor", "BorderOpacity" } }, rows = { { "Frame", "castBar" } } }, rows = { "castBarPadding", "castBarBgColor", "castBarBgOpacity", "castBarBorder", "castBarBorderSize", "castBarBorderColor", "castBarBorderOpacity" } },
      { key = "trackBackgroundCard", name = "Track background", icon = { glyph = "square" }, advanced = true, table = { cols = { { "Background", "TrackBgColor", "TrackBgOpacity" }, { "Border", "TrackBorderColor", "TrackBorderOpacity" } }, rows = { { "Cast bar", "castBar" } } }, rows = { "castBarTrackBgColor", "castBarTrackBgOpacity", "castBarTrackBorderColor", "castBarTrackBorderOpacity" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", enabled = "Totem tracker", castBarAutoShotColor = "Auto Shot wind-up colour" },
    desc = { showAutoShotBar = "The tall ranged bar with the icon, clip ticks and rotation text.", showMeleeBar = "The melee swing timer, with the Raptor Strike icon.", forceShaman = "Show the panel with no shaman in the group, for placing it." },
  },
  {
    path = "hud.classic.cooldownGrid",
    cards = {
      { key = "gridCard", name = "Grid", icon = { spell = C.KILL_COMMAND }, desc = "Icons per row; the grid grows downward.", actions = { "resetOrder" }, rows = { "cols", "rows", "resetOrder" } },
      { key = "activeHighlightCard", name = "Active highlight", icon = { glyph = "sparkle" }, rows = { "cooldownActiveStyle", "cooldownActiveColor", "cooldownActiveSize", "cooldownActiveFit", "activePreview" } },
      { key = "addAnEntryCard", name = "Add an entry", icon = { glyph = "plus" }, desc = "A spell or item ID; the label is optional.", form = { "addType", "addId", "addProc", "addLabel", "addBtn" }, rows = { "addType", "addId", "addProc", "addLabel", "addBtn" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", enabled = "Totem tracker", castBarAutoShotColor = "Auto Shot wind-up colour" },
    desc = { showAutoShotBar = "The tall ranged bar with the icon, clip ticks and rotation text.", showMeleeBar = "The melee swing timer, with the Raptor Strike icon.", forceShaman = "Show the panel with no shaman in the group, for placing it." },
  },
  {
    path = "hud.classic.totemTracker",
    cards = {
      { key = "totemTrackerCard", name = "Totem tracker", icon = { glyph = "signal" }, desc = "Air and Earth totem range, glued to the HUD's right edge; React and Fluffy show totems in their buff row instead.", rows = { "enabled", "forceShaman" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", enabled = "Totem tracker", castBarAutoShotColor = "Auto Shot wind-up colour" },
    desc = { showAutoShotBar = "The tall ranged bar with the icon, clip ticks and rotation text.", showMeleeBar = "The melee swing timer, with the Raptor Strike icon.", forceShaman = "Show the panel with no shaman in the group, for placing it." },
  },
  {
    path = "hud.fluffy.tabSize",
    cards = {
      { key = "sizeCard", name = "Size", icon = { glyph = "expand" }, rows = { "fluffyWidth", "fluffyScale" } },
      { key = "lanesCard", name = "Lanes", icon = { spell = C.STEADY_SHOT }, desc = "The flat stack, top to bottom.", rows = { "fluffyShowCast", "fluffyShowAutoShotCast", "fluffyShowSwing", "fluffyShowRanged", "fluffyShowMelee", "fluffyShowLaneIcons", "fluffyShowRange", "fluffyShowMana", "fluffyShotWindow" } },
      { key = "manaCard", name = "Mana", icon = { spell = 34074 }, rows = { "fluffyManaText", "fluffyManaTick", "fluffyManaTickDirCombat", "fluffyManaTickDirOoc" } },
      { key = "castBarCard", name = "Cast bar", icon = { spell = C.STEADY_SHOT }, rows = { "castBarNonCombatCasts" } },
      { key = "orderCard", name = "Order", icon = { glyph = "stack" }, actions = { "order_reset" }, rows = { "order_lbl_1", "order_up_1", "order_dn_1", "order_lbl_2", "order_up_2", "order_dn_2", "order_lbl_3", "order_up_3", "order_dn_3", "order_lbl_4", "order_up_4", "order_dn_4", "order_lbl_5", "order_up_5", "order_dn_5", "order_reset" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", fluffyColorAutoShotFill = "Cast: Auto Shot wind-up" },
  },
  {
    path = "hud.fluffy.tabGrid",
    cards = {
      { key = "gridCard", name = "Grid", icon = { spell = C.KILL_COMMAND }, actions = { "fcd_reset" }, rows = { "fluffyShowGrid", "fcd_add", "reactKcProcGlow", "reactRaptorGoGlow", "fcd_reset" } },
      { key = "tintsCard", name = "Tints", icon = { glyph = "palette" }, advanced = true, rows = { "reactRangeTint", "reactTileDim", "reactManaTint" } },
      { key = "activeHighlightCard", name = "Active highlight", icon = { glyph = "sparkle" }, rows = { "fluffyActiveStyle", "fluffyActiveColor", "fluffyActiveSize", "fluffyActiveFit", "activePreview" } },
      { key = "addAnEntryCard", name = "Add an entry", icon = { glyph = "plus" }, desc = "A spell or item ID; the label is optional.", form = { "addType", "addId", "addProc", "addLabel", "addBtn" }, rows = { "addType", "addId", "addProc", "addLabel", "addBtn" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", fluffyColorAutoShotFill = "Cast: Auto Shot wind-up" },
  },
  {
    path = "hud.fluffy.tabSkin",
    cards = {
      { key = "barsFontsCard", name = "Bars & fonts", icon = { glyph = "text" }, advanced = true, actions = { "resetSkin" }, rows = { "fluffyBarTexture", "fluffyFont", "fluffyFontSize", "fluffyCastH", "fluffySwingH", "fluffyRangedH", "fluffyMeleeH", "fluffyRangeH", "fluffyManaH", "resetSkin" } },
      { key = "autoShotColoursCard", name = "Auto Shot colours", icon = { spell = C.AUTO_SHOT }, advanced = true, rows = { "fluffyColorSwingFill", "fluffyColorTickSteady", "fluffyColorTickMulti", "fluffyColorTickWindup", "fluffyColorGcdDivider", "fluffyColorBracket", "fluffyColorSpark" } },
      { key = "laneColoursCard", name = "Lane colours", icon = { spell = C.MULTI_SHOT }, advanced = true, rows = { "fluffyColorSteady", "fluffyColorQueue", "fluffyColorQueueLive", "fluffyColorMulti", "fluffyColorArcane", "fluffyColorDanger", "fluffyColorRaptor", "fluffyColorWeaveAuto" } },
      { key = "manaCastCard", name = "Mana & cast", icon = { spell = 34074 }, advanced = true, rows = { "fluffyColorCastFill", "fluffyColorManaFill", "fluffyColorManaTick", "fluffyColorAutoShotFill" } },
      { key = "rangeColoursCard", name = "Range colours", icon = { spell = C.HUNTERS_MARK }, advanced = true, rows = { "fluffyColorRangeDeadzone", "fluffyColorRangeSweet", "fluffyColorRangePerfect", "fluffyColorRangeClose", "fluffyColorRangeResync" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", fluffyColorAutoShotFill = "Cast: Auto Shot wind-up" },
  },
  {
    path = "utilities.garment",
    cards = {
      { key = "bossGarmentAutopilotCard", name = "Boss garment autopilot", icon = { glyph = "shirt" }, desc = "Keeps your shirt or tabard in the state your Weave Bind macros need; needs Weave Bind on and a Shirt/Tabard line in a macro.", rows = { "weaveBindGarmentAutoFlip", "weaveBindGarmentAutoReequip" } },
    },
    rename = { weaveBindGarmentAutoFlip = "Set it for bosses", weaveBindGarmentAutoReequip = "Switch it back after the fight" },
    desc = { weaveBindGarmentAutoFlip = "On targeting a raid boss out of combat, the gate garment goes to the state your macros need.", weaveBindGarmentAutoReequip = "Once no living boss is targeted, the garment returns to its everyday state." },
  },
  {
    path = "general",
    cards = {
      { key = "framesCard", name = "Frames", icon = { glyph = "lock" }, desc = "Lock, unlock and scale every Nock frame at once; the settings window has its own scale.", actions = { "resetPos" }, rows = { "lockAll", "unlockAll", "scale", "settingsScale", "resetPos" } },
      { key = "setupCard", name = "Setup", icon = { glyph = "wrench" }, rows = { "runWizard", "minimapIcon", "perfPanel" } },
      { key = "editGridCard", name = "Edit grid", icon = { glyph = "grid" }, desc = "The raster under frames while they are unlocked.", advanced = true, rows = { "editGridShow", "editGridSize", "editGridSnap", "editSnapBy" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", settingsScale = "Settings window" },
  },
  {
    path = "general.grpLook",
    cards = {
      { key = "hudLookCard", name = "HUD look", icon = { glyph = "style" }, desc = "Classic rows, the React replica or the compact FluffyHUD cluster; each look keeps its own pages under HUD & Bars.", rows = { "hudMode", "reactNote" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", settingsScale = "Settings window" },
  },
  {
    path = "general.grpVisibility",
    cards = {
      { key = "visibilityCard", name = "Visibility", icon = { glyph = "eyeoff" }, desc = "Fade the HUD by combat state or hide it between fights; applies while frames are locked.", stack = true, rows = { "opacityNote", "opacity", "opacityOoc", "hideOoc" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", settingsScale = "Settings window" },
  },
  {
    path = "alerts.helpers.tabSettings",
    cards = {
      { key = "panelCard", name = "Panel", icon = { glyph = "pill" }, actions = { "helpersResetPos" }, rows = { "masterToggle", "parseMode", "helpersClickToApply", "helpersExpiringThreshold", "helpersIconSize", "helpersScale", "helpersResetPos" } },
      { key = "hideWhenCard", name = "Hide when", icon = { glyph = "eyeoff" }, advanced = true, rows = { "helpersHideWA", "helpersHeadline", "helpersIconGap" } },
      { key = "eatingPillCard", name = "Eating pill", icon = { glyph = "utensils" }, actions = { "consumeBannerResetPos" }, rows = { "consumeBannerEnabled", "consumeBannerSound", "consumeBannerSize", "consumeBannerResetPos" } },
      { key = "backgroundCard", name = "Background", icon = { glyph = "square" }, advanced = true, rows = { "helpersBgColor", "helpersBgOpacity", "helpersBorder", "helpersBorderSize", "helpersBorderColor", "helpersBorderOpacity" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)" },
  },
  {
    path = "utilities.mailbox",
    cards = {
      { key = "mailboxHelperCard", name = "Mailbox helper", icon = { item = 17202 }, desc = "Snowball mail at a mailbox: report, return all, or loot and send to another character.", rows = { "enabled", "keepCount" } },
      { key = "sendRecipientsCard", name = "Send recipients", icon = { glyph = "envelope" }, desc = "Characters snowballs can be mailed to, spelled as in-game.", rows = { "recipients" } },
    },
    rename = { enabled = "Mailbox helper", keepCount = "Keep snowballs in bags", recipients = "Recipients" },
    desc = { recipients = "Add a character name, one per line; twelve stacks go per mail.", keepCount = "Snowballs a send run leaves in your bags (raid supply)." },
  },
  {
    path = "pvp.pvpMode",
    cards = {
      { key = "modeCard", name = "Mode", icon = { glyph = "shield" }, desc = "Off, On, or Auto for battlegrounds and arenas. /nock pvp toggles it; a manual On survives a relog.", rows = { "pvpMode", "pvpAutoWorldFlag", "pvpBadge" } },
      { key = "panelsCard", name = "Panels", icon = { glyph = "eyeoff" }, desc = "What goes away while the mode is on. Nothing here can be used in an arena; the buff tracker still earns its place.", rows = { "pvpHideMisdirect", "pvpHideBuffTracker", "pvpHideHelpers" } },
      { key = "alertsCard", name = "Alerts", icon = { glyph = "warn" }, desc = "Raid furniture stays quiet, and the PvP trinket is the right trinket.", rows = { "pvpMuteRaidWarnings", "pvpNoAggro", "warnNoPvpTrinketEnabled" } },
      { key = "weaveBindCard", name = "Weave bind", icon = { glyph = "keyboard" }, desc = "The auto-backpedal line is a raid trick; it leaves the live macro while the mode is on.", rows = { "pvpWeaveNoMovePad" } },
      { key = "incomingCcCard", name = "Incoming CC", icon = { glyph = "bell" }, desc = "A hostile starts casting crowd control at you: FD! and that spell's sound, once per cast. Add your own by name or spell id.", form = { "pvpCcAddSpell", "pvpCcAddSound", "pvpCcAddBtn" }, table = { cols = { { "Sound" }, { "Preview" }, { "On" }, { "" } }, rows = { { "pvpCcItem_*", { ["Sound"] = "_sound", ["Preview"] = "_play", ["On"] = "_on", [""] = "_rm" } } } }, rows = { "pvpCcEnabled", "pvpCcOnlyAtYou", "pvpCcAddSpell", "pvpCcAddSound", "pvpCcAddBtn", "pvpCcItem_*" } },
      { key = "debuffTrackerCard", name = "Debuff tracker", icon = { glyph = "stack" }, desc = "PvP mode has its own set of tracked target debuffs, filtered by who is with you.", table = { cols = { { "On" } }, rows = { { "pvpdbf_*", { ["On"] = "_on" } } }, grid = 3 }, rows = { "pvpShowDebuffTracker", "pvpDebuffPartyFilter", "pvpdbf_*" } },
    },
    rename = { pvpMode = "PvP mode", pvpAutoWorldFlag = "Auto counts a world PvP flag", pvpBadge = "PVP tag on screen", pvpHideMisdirect = "Hide the Misdirection tracker", pvpHideBuffTracker = "Hide the buff tracker", pvpHideHelpers = "Hide the helper row", pvpMuteRaidWarnings = "Mute raid-only warnings", pvpNoAggro = "No aggro flash", warnNoPvpTrinketEnabled = "PvP trinket left in the bags", pvpWeaveNoMovePad = "Drop the backpedal line", pvpShowDebuffTracker = "Debuff tracker on in PvP mode", pvpDebuffPartyFilter = "Only debuffs your party can apply", pvpCcEnabled = "Incoming CC alert", pvpCcOnlyAtYou = "Only casts aimed at you", pvpCcAddSpell = "Spell name or id", pvpCcAddSound = "Sound", pvpCcAddBtn = "Add spell" },
  },
  {
    path = "utilities.qol",
    cards = {
      { key = "atAVendorCard", name = "At a vendor", icon = { glyph = "cart" }, desc = "Both run the moment a merchant window opens; chat gets one line with the cost or the total.", rows = { "qolAutoRepair", "qolSellGreys" } },
      { key = "screenCard", name = "Screen", icon = { glyph = "eyeoff" }, desc = "The full-screen glow and drunk blur, off for good.", rows = { "qolNoGlow" } },
    },
    rename = { qolAutoRepair = "Auto repair", qolSellGreys = "Sell grey items", qolNoGlow = "Full-screen glow off" },
  },
  {
    path = "hud.react.tabSize",
    cards = {
      { key = "sizeCard", name = "Size", icon = { glyph = "expand" }, rows = { "reactWidth", "reactScale" } },
      { key = "elementsCard", name = "Elements", icon = { spell = C.RAPID_FIRE }, desc = "What the cluster stacks, top to bottom.", rows = { "reactShowAutoBar", "reactShowMeleeBar", "reactMeleeStageCue", "stagePreview", "reactShowRangeBar", "reactShowManaBar", "reactShowCastBar", "reactShowGrid" } },
      { key = "manaCard", name = "Mana", icon = { spell = 34074 }, rows = { "reactManaText", "reactManaTick", "reactManaTickDirCombat", "reactManaTickDirOoc" } },
      { key = "castBarCard", name = "Cast bar", icon = { spell = C.STEADY_SHOT }, rows = { "reactShowAutoShotCast", "castBarNonCombatCasts" } },
      { key = "cornersCard", name = "Corners", icon = { spell = 13165 }, desc = "Aspect and Hunter's Mark flanking the cluster.", rows = { "reactShowAspectIcon", "reactShowMarkIcon" } },
      { key = "orderCard", name = "Order", icon = { glyph = "stack" }, actions = { "order_reset" }, rows = { "order_lbl_1", "order_up_1", "order_dn_1", "order_lbl_2", "order_up_2", "order_dn_2", "order_lbl_3", "order_up_3", "order_dn_3", "order_lbl_4", "order_up_4", "order_dn_4", "order_reset" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", reactColorAutoFill = "Auto Shot fill", reactColorAutoShotFill = "Cast: Auto Shot wind-up" },
  },
  {
    path = "hud.react.tabGrid",
    cards = {
      { key = "gridCard", name = "Grid", icon = { spell = C.KILL_COMMAND }, actions = { "rcd_reset" }, rows = { "reactConsumablesAlways", "reactKcProcGlow", "reactRaptorGoGlow", "kcActionBarGlow", "rcd_reset" } },
      { key = "tintsCard", name = "Tints", icon = { glyph = "palette" }, advanced = true, rows = { "reactRangeTint", "reactTileDim", "reactManaTint" } },
      { key = "activeHighlightCard", name = "Active highlight", icon = { glyph = "sparkle" }, rows = { "reactActiveStyle", "reactActiveColor", "reactActiveSize", "reactActiveFit", "activePreview" } },
      { key = "addAnEntryCard", name = "Add an entry", icon = { glyph = "plus" }, desc = "A spell or item ID; the label is optional.", form = { "addType", "addId", "addProc", "addLabel", "addBtn" }, rows = { "addType", "addId", "addProc", "addLabel", "addBtn" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", reactColorAutoFill = "Auto Shot fill", reactColorAutoShotFill = "Cast: Auto Shot wind-up" },
  },
  {
    path = "hud.react.tabSkin",
    cards = {
      { key = "barsFontsCard", name = "Bars & fonts", icon = { glyph = "text" }, advanced = true, actions = { "resetSkin" }, rows = { "reactBarTexture", "reactFont", "reactFontSize", "reactAutoH", "reactMeleeH", "reactRangeH", "reactManaH", "reactCastH", "reactCornerIconSize", "reactCornerIconX", "reactCornerIconY", "resetSkin" } },
      { key = "autoShotColoursCard", name = "Auto Shot colours", icon = { spell = C.AUTO_SHOT }, advanced = true, table = { cols = { { "Colour" }, { "Width" } }, rows = { { "Steady tick", { ["Colour"] = "reactColorTickSteady", ["Width"] = "reactTickSteadyWidth" } }, { "Multi tick", { ["Colour"] = "reactColorTickMulti", ["Width"] = "reactTickMultiWidth" } }, { "Wind-up mark", { ["Colour"] = "reactColorTickWindup", ["Width"] = "reactTickWindupWidth" } }, { "eWS brackets", { ["Colour"] = "reactColorBracket", ["Width"] = "reactBracketWidth" } }, { "GCD divider", { ["Colour"] = "reactColorGcdDivider", ["Width"] = "reactGcdDividerWidth" } } } }, rows = { "reactColorAutoFill", "reactTickSteadyWidth", "reactColorTickSteady", "reactTickMultiWidth", "reactColorTickMulti", "reactTickWindupWidth", "reactColorTickWindup", "reactBracketWidth", "reactColorBracket", "reactGcdDividerWidth", "reactColorGcdDivider" } },
      { key = "meleeColoursCard", name = "Melee colours", icon = { spell = C.RAPTOR_STRIKE }, advanced = true, rows = { "reactColorMeleeReady", "reactColorMeleeAuto" } },
      { key = "manaCastCard", name = "Mana & cast", icon = { spell = 34074 }, advanced = true, rows = { "reactColorManaFill", "reactColorManaTick", "reactColorCastFill", "reactColorAutoShotFill" } },
      { key = "rangeColoursCard", name = "Range colours", icon = { spell = C.HUNTERS_MARK }, advanced = true, table = { cols = { { "Colour" }, { "Width" } }, rows = { { "Deadzone", { ["Colour"] = "reactColorRangeDeadzone" } }, { "Sweet", { ["Colour"] = "reactColorRangeSweet" } }, { "Perfect", { ["Colour"] = "reactColorRangePerfect" } }, { "Close", { ["Colour"] = "reactColorRangeClose" } }, { "RESYNC", { ["Colour"] = "reactColorRangeResync" } }, { "Divider", { ["Colour"] = "reactColorRangeDivider", ["Width"] = "reactRangeDividerWidth" } } } }, rows = { "reactColorRangeDeadzone", "reactColorRangeSweet", "reactColorRangePerfect", "reactColorRangeClose", "reactColorRangeResync", "reactRangeDividerWidth", "reactColorRangeDivider" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", reactColorAutoFill = "Auto Shot fill", reactColorAutoShotFill = "Cast: Auto Shot wind-up" },
  },
  {
    path = "utilities.shopping",
    cards = {
      { key = "shoppingListCard", name = "Shopping list", icon = { glyph = "cart" }, desc = "A floating panel in shopping zones with what you are short of.", actions = { "resetPos" }, rows = { "enabled", "showCompleted", "width", "resetPos", "zones" } },
      { key = "backgroundCard", name = "Background", icon = { glyph = "square" }, advanced = true, rows = { "shoppingBgColor", "shoppingBgOpacity", "shoppingBorder", "shoppingBorderSize", "shoppingBorderColor", "shoppingBorderOpacity" } },
      { key = "curatedItemsCard", name = "Curated items", icon = { glyph = "stack" }, desc = "Toggle each item and set the count to keep; the panel lists what is short.", actions = { "restoreDefaults" }, rows = { "restoreDefaults" } },
      { key = "customItemsCard", name = "Custom items", icon = { glyph = "plus" }, desc = "Anything the curated list does not cover; it shows on the panel like the rest.", form = { "customAddId", "customAddThr", "customAddLabel", "customAddBtn" }, rows = { "customAddId", "customAddThr", "customAddLabel", "customAddBtn", "customItem_*", "custom" } },
      { key = "repairReminderCard", name = "Repair reminder", icon = { glyph = "wrench" }, rows = { "repairEnabled", "repairPct" } },
    },
    rename = { enabled = "Shopping list", showCompleted = "Stocked items too", repairEnabled = "Repair reminder" },
  },
  {
    path = "alerts.sounds.deadZone",
    cards = {
      { key = "deadZoneCard", name = "Dead zone", icon = { glyph = "bell" }, table = { cols = { { "On" }, { "Sound" }, { "Preview" } }, rows = { { "Entering", { ["On"] = "deadZoneEnterEnabled", ["Sound"] = "deadZoneEnterSound", ["Preview"] = "deadZoneEnterPreview" } }, { "Leaving", { ["On"] = "deadZoneExitEnabled", ["Sound"] = "deadZoneExitSound", ["Preview"] = "deadZoneExitPreview" } } } }, rows = { "intro", "deadZoneEnterEnabled", "deadZoneEnterSound", "deadZoneEnterPreview", "deadZoneExitEnabled", "deadZoneExitSound", "deadZoneExitPreview", "deadZoneSoundChannel" } },
    },
    rename = { consumeBannerSound = "Chime when Well Fed lands", deadZoneSoundChannel = "Output channel", aggroSoundMode = "Aggro cue", aggroPreview = "Preview aggro cue" },
    desc = { deadZoneSoundChannel = "The audio channel the dead-zone cues play through; Master ignores the music and ambience sliders." },
  },
  {
    path = "alerts.sounds.weave",
    cards = {
      { key = "weavingCard", name = "Weaving", icon = { glyph = "sparkle" }, table = { cols = { { "On" }, { "Sound" }, { "Preview" } }, rows = { { "Raptor Strike hit", { ["On"] = "weaveRaptorHitEnabled", ["Sound"] = "weaveRaptorHitSound", ["Preview"] = "weaveRaptorHitPreview" } }, { "Windfury proc", { ["On"] = "weaveWfProcEnabled", ["Sound"] = "weaveWfProcSound", ["Preview"] = "weaveWfProcPreview" } } } }, rows = { "intro", "weaveRaptorHitEnabled", "weaveRaptorHitSound", "weaveRaptorHitPreview", "weaveWfProcEnabled", "weaveWfProcSound", "weaveWfProcPreview" } },
    },
    rename = { consumeBannerSound = "Chime when Well Fed lands", deadZoneSoundChannel = "Output channel", aggroSoundMode = "Aggro cue", aggroPreview = "Preview aggro cue" },
    desc = { deadZoneSoundChannel = "The audio channel the dead-zone cues play through; Master ignores the music and ambience sliders." },
  },
  {
    path = "alerts.sounds.warnings",
    cards = {
      { key = "warningsCard", name = "Warnings", icon = { glyph = "warn" }, table = { cols = { { "Sound" }, { "Preview" } }, rows = { { "Dazed", { ["Sound"] = "media_warnDazedSound", ["Preview"] = "mediaplay_warnDazedSound" } }, { "Feign Death resisted", { ["Sound"] = "media_warnFDResistSound", ["Preview"] = "mediaplay_warnFDResistSound" } }, { "Boss mark", { ["Sound"] = "media_warnBossMarkSound", ["Preview"] = "mediaplay_warnBossMarkSound" } }, { "Slammer: caught exposed", { ["Sound"] = "media_warnSlammerSound", ["Preview"] = "mediaplay_warnSlammerSound" } }, { "Slammer: window opens", { ["Sound"] = "media_warnSlammerWindowSound", ["Preview"] = "mediaplay_warnSlammerWindowSound" } }, { "Ripper: ALT F4", { ["Sound"] = "media_warnRipperSound", ["Preview"] = "mediaplay_warnRipperSound" } } } }, rows = { "intro", "media_*", "mediaplay_*" } },
    },
    rename = { consumeBannerSound = "Chime when Well Fed lands", deadZoneSoundChannel = "Output channel", aggroSoundMode = "Aggro cue", aggroPreview = "Preview aggro cue" },
    desc = { deadZoneSoundChannel = "The audio channel the dead-zone cues play through; Master ignores the music and ambience sliders." },
  },
  {
    path = "alerts.sounds.other",
    cards = {
      { key = "otherCuesCard", name = "Other cues", icon = { glyph = "utensils" }, actions = { "aggroPreview" }, rows = { "intro", "consumeBannerSound", "aggroSoundMode", "aggroPreview" } },
    },
    rename = { consumeBannerSound = "Chime when Well Fed lands", deadZoneSoundChannel = "Output channel", aggroSoundMode = "Aggro cue", aggroPreview = "Preview aggro cue" },
    desc = { deadZoneSoundChannel = "The audio channel the dead-zone cues play through; Master ignores the music and ambience sliders." },
  },
  {
    path = "alerts.warnings.settings",
    cards = {
      { key = "squaresCard", name = "Squares", icon = { glyph = "warn" }, desc = "The alert squares; drag the row while frames are unlocked, Reset puts it back top centre.", actions = { "warningsResetPosition" }, rows = { "warningsResetPosition", "warningIconSize", "warningBorderSize" } },
      { key = "labelsCard", name = "Labels", icon = { glyph = "text" }, advanced = true, stack = true, rows = { "warningLabelOffset", "warningLabelSize", "warningLabelFont", "warningLabelStyle", "warningLabelUpper" } },
      { key = "previewCard", name = "Preview", icon = { glyph = "play" }, desc = "Fire a sample so you can dial in size, fonts, offset and thickness without waiting for a real trigger.", stack = true, rows = { "previewButton", "noReleasePreview" } },
    },
    rename = { showAutoShotBar = "Auto Shot bar", showMeleeBar = "Melee swing timer", showGcdBar = "GCD bar", showManaBar = "Mana bar", rotationHelperEnabled = "Rotation helper", showWindupMark = "Wind-up mark", editGridShow = "Grid while unlocked", showAutoShotCast = "Auto Shot in cast bar", castBarNonCombatCasts = "Non-combat casts", backgroundEnabled = "Background", consumeBannerEnabled = "Pill while eating or drinking", playerEnabled = "Player buffs panel", petEnabled = "Pet buffs panel", trackerEnabled = "Tracker section", clickerEnabled = "Tank buttons", showCompleted = "Stocked items too", repairEnabled = "Repair reminder", weaveBindEnabled = "Weave bind", tonkDialEnabled = "Countdown dial", practiceToast = "Toast", practiceTimelineOkMarks = "OK marks too", releaseBarEnabled = "Retry-Timer", fluffyShowAutoShotCast = "Auto Shot wind-up as a cast", shotBarsShowMulti = "Multi-Shot window", shotBarsShowArcane = "Arcane Shot window", shotBarsShowRaptor = "Melee weave lane", autoShotDelayEnabled = "Auto Shot delay (experimental)", previewButton = "Sample warnings", noReleasePreview = "DO NOT RELEASE banner" },
    desc = { previewButton = "One red, one amber, one blue for ten seconds.", noReleasePreview = "The centre-screen wipe-with-Bloodlust banner for five seconds, so you can place it without dying for it." },
  },
  {
    path = "utilities.weaveBind",
    cards = {
      { key = "weaveKeyCard", name = "Weave key", icon = { spell = C.RAPTOR_STRIKE }, desc = "Hold the key to step in for a Raptor Strike and back out; experimental.", rows = { "weaveBindEnabled", "weaveBindKey", "weaveLogPanel" } },
      { key = "pressMacroBuilderCard", name = "Press macro builder", icon = { item = 17202 }, desc = "The same switches the setup wizard offers; they edit the press macro below.", rows = { "weaveSnowball", "weaveSnowballGate", "weaveGateGarment", "weaveGateDirection", "weaveMovePad" } },
      { key = "macrosCard", name = "Macros", icon = { glyph = "keyboard" }, desc = "Run on key press and on release (255 characters each). The shirt/tabard autopilot lives under Boss Garment.", advanced = true, actions = { "weaveBindRestore" }, segments = { label = "Quick fill", desc = "Replaces both bodies with a solid base; edit from there.", options = { { "Default", "the shipped weave pair", "weaveFillDefault" }, { "Natty", "empty, type your own", "weaveFillNatty" }, { "Clever", "backpedal + snowball gate", "weaveFillClever" } } }, rows = { "weaveFillDefault", "weaveFillNatty", "weaveFillClever", "weaveBindMacroDown", "weaveBindMacroUp", "weaveBindRestore" } },
    },
    rename = { weaveBindEnabled = "Weave bind", weaveBindMacroDown = "On press", weaveBindMacroUp = "On release", weaveSnowballGate = "Only when the garment says so" },
    desc = { weaveBindEnabled = "Master switch for the weave key.", weaveBindMacroDown = "", weaveBindMacroUp = "" },
  },
}

return L
