-- UI/Frame_AspectRing.lua
-- The ring view factory (a layer and n secure slot buttons with the React tile look, WoW Forever) and the aspect ring's own view.

local Nock = LibStub("AceAddon-3.0"):GetAddon("Nock")
local C = Nock.Constants

local SLOT = 36
local HOVER_SCALE = 1.12
local IDLE_BORDER = { 0, 0, 0, 1 }
-- Style B (mockup pick, 2026-09-24): a dark disc with its track line and
-- centre cap, a 60-degree pointer wedge toward the pick, the name below.
-- Both textures are the disc's size (Nock.AspectRingGeometry: 150 for six
-- slots, 178 for eight; non-power-of-two, drawn 1:1), generated by
-- Tests/tools/aspect_ring_media.py.
local MEDIA = "Interface\\AddOns\\Nock\\Media\\"
local WEDGE_ALPHA = 0.22
local NAME_GAP = 5   -- the name's top edge below the disc
-- No-mana tint: the React grid's blue (UI/Frame_ReactCooldowns.lua TINT).
local MANA_TINT = { 0.33, 0.54, 1, 1 }
local NO_TINT   = { 1, 1, 1, 1 }

-- `spec` (see Forever/AspectRing.lua, Nock.NewRingModule for the module's):
--   name        the view module's name ("AspectRingView")
--   layer       the layer's global name; slots are <slotPrefix>1..n
--   stateKey    the Nock.state slot the module publishes ("aspectRing")
--   n           slots (the disc and wedge textures must match: the disc's
--               size for n, a 360/n-degree wedge)
--   disc        the disc's file name under Media
--   wedge       the pointer wedge's file name under Media
--   closeMsg    the message a slot click sends
--   scaleProfile the size's profile key
--   idByKey()   slot key -> spell id
--   activeKey(state)  the slot key that is up right now, or nil
function Nock.NewRingView(spec)
local View = Nock:NewModule(spec.name, "AceEvent-3.0")
local SLICE = 2 * math.pi / spec.n
local _, RADIUS, DISC_SIZE = Nock.AspectRingGeometry(spec.n)

-- Its own UIParent layer (the Helpers click-layer precedent): a hidden HUD
-- must not take the ring with it, and secure buttons stay out of the HUD
-- tree. The secure slots make it protected, so the key's snippet shows, moves
-- and hides it (Forever/AspectRing.lua, in combat too); this view paints.
--
-- Only creation happens here: a /reload in combat loads the addon under the
-- lockdown, so every call on a secure button waits for SetupSlots (the first
-- out-of-combat open).
function View:OnInitialize()
  local layer = CreateFrame("Frame", spec.layer, UIParent)
  layer:SetFrameStrata("DIALOG")
  layer:SetSize(1, 1)
  layer:Hide()
  self.layer = layer

  -- The disc carries the centre cap (radius 17, outside the cancel radius
  -- 14), so everything that looks like cancel is cancel.
  local disc = layer:CreateTexture(nil, "BACKGROUND")
  disc:SetTexture(MEDIA .. spec.disc)
  disc:SetSize(DISC_SIZE, DISC_SIZE)
  disc:SetPoint("CENTER", layer, "CENTER", 0, 0)
  self.disc = disc

  -- Points straight up in the file; SetRotation turns it counter-clockwise,
  -- so slot i (clockwise from up) is -(i - 1) * 60 degrees.
  local wedge = layer:CreateTexture(nil, "BORDER")
  wedge:SetTexture(MEDIA .. spec.wedge)
  wedge:SetSize(DISC_SIZE, DISC_SIZE)
  wedge:SetPoint("CENTER", layer, "CENTER", 0, 0)
  wedge:Hide()
  self.wedge = wedge

  local name = layer:CreateFontString(nil, "OVERLAY")
  Nock.UI.ApplyReactTextLook(name)
  name:SetPoint("TOP", layer, "CENTER", 0, -(DISC_SIZE / 2 + NAME_GAP))
  name:SetJustifyH("CENTER")
  name:SetText("")
  self.name = name

  self.idByKey = spec.idByKey()
  self.slots = {}
  self.items = {}
  for i = 1, spec.n do
    local b = CreateFrame("Button", spec.slotPrefix .. i, layer, "SecureActionButtonTemplate")
    b:SetScript("PostClick", function() View:SendMessage(spec.closeMsg) end)
    -- The tile hangs off its centre (not all four corners), so the hover
    -- SetScale grows it about the middle.
    local tile = Nock.UI.CreateReactSlot(b, nil, SLOT)
    tile:SetPoint("CENTER", b, "CENTER", 0, 0)
    tile:Show()
    b.tile = tile
    self.slots[i] = b
    self.items[i] = { icon = nil, exp = 0, dur = 0, desat = false }
  end
  -- The name follows the React font settings live.
  self:RegisterMessage("NOCK_VISUALS_CHANGED", function() Nock.UI.ApplyReactTextLook(self.name) end)
end

-- Size, place and wire the secure slots, once, out of combat.
function View:SetupSlots()
  for i, b in ipairs(self.slots) do
    b:SetSize(SLOT, SLOT)
    b:RegisterForClicks("AnyUp")
    b:SetAttribute("useOnKeyDown", false)
    local ox, oy = Nock.AspectRingSlotOffset(i, RADIUS, spec.n)
    b:SetPoint("CENTER", self.layer, "CENTER", ox, oy)
  end
  self._setup = true
end

-- Attributes per slot from the state's known names, out of combat only.
function View:ApplyKnown(st)
  for i, b in ipairs(self.slots) do
    local macro = Nock.AspectRingMacro(st.known[i])
    if macro then
      b:SetAttribute("type", "macro")
      b:SetAttribute("macrotext", macro)
      b:EnableMouse(true)
    else
      b:SetAttribute("type", nil)
      b:SetAttribute("macrotext", nil)
      b:EnableMouse(false)
    end
  end
  self._knownRev = st.knownRev
end

-- The secure side, out of combat only and ahead of use (the ring can open
-- in combat now, when none of it may be touched): the slots, their casts and
-- the ring size (the layer's scale; the snippet divides its cursor spot by
-- the same value).
function View:SecureSetup(st)
  if InCombatLockdown() then return end
  if not self._setup then self:SetupSlots() end
  if st.knownRev ~= self._knownRev then self:ApplyKnown(st) end
  local scale = Nock.RingScale(Nock.db and Nock.db.profile, spec.scaleProfile)
  if scale ~= self._scale then
    self.layer:SetScale(scale)
    self._scale = scale
  end
end

function View:Refresh(state)
  local st = state[spec.stateKey]
  self:SecureSetup(st)
  if not st.open then return end

  local activeKey = spec.activeKey(state)
  local p = (Nock.db and Nock.db.profile) or {}
  local glow = p.reactActiveColor or C.COLORS.PROC_GLOW
  local depth = (p.reactActiveSize or 3) * 3
  local now = GetTime()
  local order = st.order
  for i, b in ipairs(self.slots) do
    local key = order[i]
    local it = self.items[i]
    local learned = st.known[i] ~= nil
    it.icon = learned and key and Nock.API.SpellIcon(self.idByKey[key]) or nil
    -- A learned aspect the mana does not cover: the cooldown grid's no-mana
    -- look (blue, desaturated). Only the module with a mana read publishes it.
    local noMana = (learned and st.noMana and st.noMana[i] == true) or false
    it.desat = not learned or noMana
    Nock.UI.PaintReactSlot(b.tile, it, now)
    if noMana ~= (b._noMana or false) then
      local c = noMana and MANA_TINT or NO_TINT
      b.tile.icon:SetVertexColor(c[1], c[2], c[3], c[4])
      b._noMana = noMana
    end
    Nock.UI.SetIconInsetGlow(b.tile, (learned and key == activeKey) and glow or nil, depth)
    local hovered = st.hover == i
    if hovered ~= b._hovered then
      b.tile:SetScale(hovered and HOVER_SCALE or 1)
      local c = hovered and glow or IDLE_BORDER
      b.tile:SetBackdropBorderColor(c[1], c[2], c[3], c[4] or 1)
      b._hovered = hovered
    end
  end

  -- Pointer and name follow the pick; both repaint only when it moves.
  local h = st.hover
  if h ~= self._hover or glow ~= self._wedgeColor then
    if h then
      self.wedge:SetRotation(-(h - 1) * SLICE)
      self.wedge:SetVertexColor(glow[1], glow[2], glow[3], WEDGE_ALPHA)
      self.wedge:Show()
    else
      self.wedge:Hide()
    end
    self.name:SetText(h and st.short and st.short[h] or "")
    self._hover, self._wedgeColor = h, glow
  end
end

return View
end

-- The aspect ring's view. The active aspect comes from the aura reader.
Nock.NewRingView({
  name = "AspectRingView", layer = "NockAspectRingLayer", slotPrefix = "NockAspectRingSlot",
  stateKey = "aspectRing", n = 6, disc = "AspectRingDisc.tga", wedge = "AspectRingWedge.tga",
  closeMsg = "NOCK_ASPECT_RING_CLOSE", scaleProfile = "aspectRingScale",
  idByKey = Nock.AspectRingIdByKey,
  activeKey = function(state)
    local active = state.player and state.player.aspect and state.player.aspect.spellId
    return active and Nock.Spells.ASPECTS[active] or nil
  end,
})
