-- UI/Frame_AspectRing.lua
-- The aspect ring's layer and six secure slot buttons with the React tile look (WoW Forever).

local Nock = LibStub("AceAddon-3.0"):GetAddon("Nock")
local View = Nock:NewModule("AspectRingView", "AceEvent-3.0")
local C = Nock.Constants

local SLOT = 36
local HOVER_SCALE = 1.12
local IDLE_BORDER = { 0, 0, 0, 1 }
-- Style B (mockup pick, 2026-09-24): a dark disc with its track line and
-- centre cap, a 60-degree pointer wedge toward the pick, the name below.
-- Both textures are 150x150 (non-power-of-two, drawn 1:1), generated by
-- Tests/tools/aspect_ring_media.py.
local MEDIA = "Interface\\AddOns\\Nock\\Media\\"
local DISC_SIZE = 150
local WEDGE_ALPHA = 0.22
local NAME_OFFSET = -80   -- the name's top edge below the ring centre
local SLICE = 2 * math.pi / 6

-- Its own UIParent layer (the Helpers click-layer precedent): a hidden HUD
-- must not take the ring with it, and secure buttons stay out of the HUD
-- tree. The secure slots make it protected, so the key's snippet shows, moves
-- and hides it (Forever/AspectRing.lua, in combat too); this view paints.
--
-- Only creation happens here: a /reload in combat loads the addon under the
-- lockdown, so every call on a secure button waits for SetupSlots (the first
-- out-of-combat open).
function View:OnInitialize()
  local layer = CreateFrame("Frame", "NockAspectRingLayer", UIParent)
  layer:SetFrameStrata("DIALOG")
  layer:SetSize(1, 1)
  layer:Hide()
  self.layer = layer

  -- The disc carries the centre cap (radius 17, outside the cancel radius
  -- 14), so everything that looks like cancel is cancel.
  local disc = layer:CreateTexture(nil, "BACKGROUND")
  disc:SetTexture(MEDIA .. "AspectRingDisc.tga")
  disc:SetSize(DISC_SIZE, DISC_SIZE)
  disc:SetPoint("CENTER", layer, "CENTER", 0, 0)
  self.disc = disc

  -- Points straight up in the file; SetRotation turns it counter-clockwise,
  -- so slot i (clockwise from up) is -(i - 1) * 60 degrees.
  local wedge = layer:CreateTexture(nil, "BORDER")
  wedge:SetTexture(MEDIA .. "AspectRingWedge.tga")
  wedge:SetSize(DISC_SIZE, DISC_SIZE)
  wedge:SetPoint("CENTER", layer, "CENTER", 0, 0)
  wedge:Hide()
  self.wedge = wedge

  local name = layer:CreateFontString(nil, "OVERLAY")
  Nock.UI.ApplyReactTextLook(name)
  name:SetPoint("TOP", layer, "CENTER", 0, NAME_OFFSET)
  name:SetJustifyH("CENTER")
  name:SetText("")
  self.name = name

  self.idByKey = Nock.AspectRingIdByKey()
  self.slots = {}
  self.items = {}
  for i = 1, #Nock.Spells.ASPECT_RING do
    local b = CreateFrame("Button", "NockAspectRingSlot" .. i, layer, "SecureActionButtonTemplate")
    b:SetScript("PostClick", function() View:SendMessage("NOCK_ASPECT_RING_CLOSE") end)
    -- The tile hangs off its centre (not all four corners), so the hover
    -- SetScale grows it about the middle.
    local tile = Nock.UI.CreateReactSlot(b, nil, SLOT)
    tile:SetPoint("CENTER", b, "CENTER", 0, 0)
    tile:Show()
    b.tile = tile
    self.slots[i] = b
    self.items[i] = { icon = nil, exp = 0, dur = 0, desat = false }
  end
  -- The name follows the React font settings live.
  self:RegisterMessage("NOCK_VISUALS_CHANGED", function() Nock.UI.ApplyReactTextLook(self.name) end)
end

-- Size, place and wire the secure slots, once, out of combat.
function View:SetupSlots()
  local _, radius = Nock.AspectRingGeometry()
  for i, b in ipairs(self.slots) do
    b:SetSize(SLOT, SLOT)
    b:RegisterForClicks("AnyUp")
    b:SetAttribute("useOnKeyDown", false)
    local ox, oy = Nock.AspectRingSlotOffset(i, radius)
    b:SetPoint("CENTER", self.layer, "CENTER", ox, oy)
  end
  self._setup = true
end

-- Attributes per slot from state.aspectRing.known, out of combat only.
function View:ApplyKnown(st)
  for i, b in ipairs(self.slots) do
    local macro = Nock.AspectRingMacro(st.known[i])
    if macro then
      b:SetAttribute("type", "macro")
      b:SetAttribute("macrotext", macro)
      b:EnableMouse(true)
    else
      b:SetAttribute("type", nil)
      b:SetAttribute("macrotext", nil)
      b:EnableMouse(false)
    end
  end
  self._knownRev = st.knownRev
end

-- The secure side, out of combat only and ahead of use (the ring can open
-- in combat now, when none of it may be touched): the slots, their casts and
-- the ring size (the layer's scale; the snippet divides its cursor spot by
-- the same value).
function View:SecureSetup(st)
  if InCombatLockdown() then return end
  if not self._setup then self:SetupSlots() end
  if st.knownRev ~= self._knownRev then self:ApplyKnown(st) end
  local scale = Nock.AspectRingScale(Nock.db and Nock.db.profile)
  if scale ~= self._scale then
    self.layer:SetScale(scale)
    self._scale = scale
  end
end

function View:Refresh(state)
  local st = state.aspectRing
  self:SecureSetup(st)
  if not st.open then return end

  local active = state.player and state.player.aspect and state.player.aspect.spellId
  local activeKey = active and Nock.Spells.ASPECTS[active]
  local p = (Nock.db and Nock.db.profile) or {}
  local glow = p.reactActiveColor or C.COLORS.PROC_GLOW
  local depth = (p.reactActiveSize or 3) * 3
  local now = GetTime()
  local order = st.order
  for i, b in ipairs(self.slots) do
    local key = order[i]
    local it = self.items[i]
    local learned = st.known[i] ~= nil
    it.icon = learned and key and Nock.API.SpellIcon(self.idByKey[key]) or nil
    it.desat = not learned
    Nock.UI.PaintReactSlot(b.tile, it, now)
    Nock.UI.SetIconInsetGlow(b.tile, (learned and key == activeKey) and glow or nil, depth)
    local hovered = st.hover == i
    if hovered ~= b._hovered then
      b.tile:SetScale(hovered and HOVER_SCALE or 1)
      local c = hovered and glow or IDLE_BORDER
      b.tile:SetBackdropBorderColor(c[1], c[2], c[3], c[4] or 1)
      b._hovered = hovered
    end
  end

  -- Pointer and name follow the pick; both repaint only when it moves.
  local h = st.hover
  if h ~= self._hover or glow ~= self._wedgeColor then
    if h then
      self.wedge:SetRotation(-(h - 1) * SLICE)
      self.wedge:SetVertexColor(glow[1], glow[2], glow[3], WEDGE_ALPHA)
      self.wedge:Show()
    else
      self.wedge:Hide()
    end
    self.name:SetText(h and st.short and st.short[h] or "")
    self._hover, self._wedgeColor = h, glow
  end
end
