-- UI/IconAtlas.lua
-- GENERATED by Tests/tools/nucleo_atlas.py from the Nucleo pixel family.
-- name -> { left, right, top, bottom } texcoords into Media/PixelIcons.tga;
-- white on transparent, tint with SetVertexColor. Nucleo icons: nucleoapp.com, licensed.
local Nock = rawget(_G, "Nock")
Nock.IconAtlas = {
  texture = "Interface\\AddOns\\Nock\\Media\\PixelIcons",
  size = { 256, 128 }, cell = 32,
  coords = {
    stage      = { 0.000000, 0.125000, 0.000000, 0.250000 },  -- square-timeline
    lesson     = { 0.125000, 0.250000, 0.000000, 0.250000 },  -- book-open
    ladder     = { 0.250000, 0.375000, 0.000000, 0.250000 },  -- steps-indicator
    review     = { 0.375000, 0.500000, 0.000000, 0.250000 },  -- chart-activity
    scenarios  = { 0.500000, 0.625000, 0.000000, 0.250000 },  -- app-stack
    style      = { 0.625000, 0.750000, 0.000000, 0.250000 },  -- brush
    focus      = { 0.750000, 0.875000, 0.000000, 0.250000 },  -- arrows-expand-diagonal-3
    play       = { 0.875000, 1.000000, 0.000000, 0.250000 },  -- media-play
    stop       = { 0.000000, 0.125000, 0.250000, 0.500000 },  -- media-stop
    pause      = { 0.125000, 0.250000, 0.250000, 0.500000 },  -- media-pause
    prev       = { 0.250000, 0.375000, 0.250000, 0.500000 },  -- media-previous
    next       = { 0.375000, 0.500000, 0.250000, 0.500000 },  -- media-next
    skipstart  = { 0.500000, 0.625000, 0.250000, 0.500000 },  -- media-skip-to-start
    skipend    = { 0.625000, 0.750000, 0.250000, 0.500000 },  -- media-skip-to-end
    replay     = { 0.750000, 0.875000, 0.250000, 0.500000 },  -- history
    close      = { 0.875000, 1.000000, 0.250000, 0.500000 },  -- xmark
    gear       = { 0.000000, 0.125000, 0.500000, 0.750000 },  -- gear
    target     = { 0.125000, 0.250000, 0.500000, 0.750000 },  -- target
    bow        = { 0.250000, 0.375000, 0.500000, 0.750000 },  -- arrow-up-right
    check      = { 0.375000, 0.500000, 0.500000, 0.750000 },  -- check
    warn       = { 0.500000, 0.625000, 0.500000, 0.750000 },  -- triangle-warning
    key        = { 0.625000, 0.750000, 0.500000, 0.750000 },  -- key
    clock      = { 0.750000, 0.875000, 0.500000, 0.750000 },  -- clock
    ghost      = { 0.875000, 1.000000, 0.500000, 0.750000 },  -- skull
    chevron    = { 0.000000, 0.125000, 0.750000, 1.000000 },  -- chevron-down
  },
  fileCell = 24,   -- the per-icon files are the bare 24-grid, no padding
  files = {
    stage      = "Interface\\AddOns\\Nock\\Media\\Icons\\stage",
    lesson     = "Interface\\AddOns\\Nock\\Media\\Icons\\lesson",
    ladder     = "Interface\\AddOns\\Nock\\Media\\Icons\\ladder",
    review     = "Interface\\AddOns\\Nock\\Media\\Icons\\review",
    scenarios  = "Interface\\AddOns\\Nock\\Media\\Icons\\scenarios",
    style      = "Interface\\AddOns\\Nock\\Media\\Icons\\style",
    focus      = "Interface\\AddOns\\Nock\\Media\\Icons\\focus",
    play       = "Interface\\AddOns\\Nock\\Media\\Icons\\play",
    stop       = "Interface\\AddOns\\Nock\\Media\\Icons\\stop",
    pause      = "Interface\\AddOns\\Nock\\Media\\Icons\\pause",
    prev       = "Interface\\AddOns\\Nock\\Media\\Icons\\prev",
    next       = "Interface\\AddOns\\Nock\\Media\\Icons\\next",
    skipstart  = "Interface\\AddOns\\Nock\\Media\\Icons\\skipstart",
    skipend    = "Interface\\AddOns\\Nock\\Media\\Icons\\skipend",
    replay     = "Interface\\AddOns\\Nock\\Media\\Icons\\replay",
    close      = "Interface\\AddOns\\Nock\\Media\\Icons\\close",
    gear       = "Interface\\AddOns\\Nock\\Media\\Icons\\gear",
    target     = "Interface\\AddOns\\Nock\\Media\\Icons\\target",
    bow        = "Interface\\AddOns\\Nock\\Media\\Icons\\bow",
    check      = "Interface\\AddOns\\Nock\\Media\\Icons\\check",
    warn       = "Interface\\AddOns\\Nock\\Media\\Icons\\warn",
    key        = "Interface\\AddOns\\Nock\\Media\\Icons\\key",
    clock      = "Interface\\AddOns\\Nock\\Media\\Icons\\clock",
    ghost      = "Interface\\AddOns\\Nock\\Media\\Icons\\ghost",
    chevron    = "Interface\\AddOns\\Nock\\Media\\Icons\\chevron",
  },
}
